### ISSUE TITLE
Doesn't convert pluralised strings correctly.

### ISSUE THREAD

**Issue by MaryBartlett** [rockykitamura/grunt-po2json#11]
Polish po file:
msgctxt "product.trackCount"
msgid "%d song"
msgid_plural "%d songs"
msgstr[0] "%d utwór"
msgstr[1] "%d utwory"
msgstr[2] "%d utworów"

Polish json file:
  "product.trackCount\u0004%d song": [
    "%d songs",
    "%d utwór",
    "%d utwory",
    "%d utworów"
  ],

I don't expect the  "%d songs" to exist in the array after conversion - have I interpreted this wrongly or is this a problem.

**Comment by JSteunou** [comment]
for all output related you should see po2json. This project is just a grunt task wrapper around it https://github.com/mikeedwards/po2json

Also there was an issue with Jed 1.1 changing the plural supported form and adding a breaking change, which is now supported by latest po2json version
