### ISSUE TITLE
Allow msgctxt to be key only - no concatenation with string

### ISSUE THREAD

**Issue by MaryBartlett** [rockykitamura/grunt-po2json#12]
Ideally it should be possible for this string in the .po file:

msgctxt "favouriteArtists.favouriteFtuMessage"
msgid "Added to your favourites."
msgstr "Dodano do Twoich ulubionych."

To be accessed as the "favouriteArtists.favouriteFtuMessage" key only - this is what occurs currently:

  "favouriteArtists.favouriteFtuMessage\u0004Added to your favourites.": [
    null,
    "Dodano do Twoich ulubionych."
  ],

Ideally there should be an option for this to be the output:

  "favouriteArtists.favouriteFtuMessage": [
    null,
    "Dodano do Twoich ulubionych."
  ],

**Comment by JSteunou** [comment]
for all output related you should see po2json. This project is just a grunt task wrapper around it https://github.com/mikeedwards/po2json
