### ISSUE TITLE
Stopped instaling via npm today 11.09.2014 - package unpublished

### ISSUE THREAD

**Issue by alex-kowalczyk** [rockykitamura/grunt-po2json#13]
Have you done any release recently? Today npm stopped installing grunt-po2json.
Tested on three machines, no other changes in dev config in the meanwhile

EDIT: npm registry says you unpublished the package. What might be a workaround?

grunt-po2json
This package has been unpublished.

Description	Convert PO files to JSON using Grunt.
Unpublished By	
rkitamura
Unpublished On	Wed Sep 10 2014 23:21:42 GMT+0000 (UTC)

$ npm install grunt-po2json
npm WARN package.json O2O@1.1.0 No repository field.
npm http GET http://registry.npmjs.org/grunt-po2json
npm http 404 http://registry.npmjs.org/grunt-po2json
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt-po2json"
npm ERR! cwd /home/alex/Documents/src
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/alex/Documents/src/npm-debug.log
npm ERR! not ok code 0

**Comment by natkuu** [comment]
Had the same problem. All you need to do is to install package directly from git: ``npm install git+https://github.com/rockykitamura/grunt-po2json.git``
It will install package directly from git.

**Comment by whyhankee** [comment]
Hi all,

@rockykitamura does not seem to answer on this issue and i would like this module to 'live on' and be published to npm once again.

I don't have a lot of experience with situations like this but i would suggest:
- Someone forks the repository (make sure it lives on)
- That same 'someone' adds a short entry to the README explaining the situation and add a link to this issue.
- that same 'someone' publishes to module back to npm.

I'm not doing very much with either Grunt and/or .po files but i would be willing to do this unless a better suited someone steps up .. 

Suggestions / Ideas?

**Comment by rockykitamura** [comment]
Sorry about that.  I have published grunt-po2json again.  I don't have much time to make improvements to it, so contributions are welcome.  Be sure to add tests when adding new features.  Thanks!

**Comment by whyhankee** [comment]
Thanks @rockykitamura, for publishing again.
I can confirm that all is as it should be.
/me happy

**Comment by JSteunou** [comment]
ty @rockykitamura !!
